tech/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
#import notifications.urls

from . import views
from .views import *


urlpatterns = [
    path('signup/', views.RegisterPage, name='register'),
    path('signin/', views.LoginPage, name='login'),
    path('update_profile/', views.ProfileUpdate, name='profile_update'),
    path('signout/', views.LogoutUser, name='logout'),
    #path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('reset_password/', 
        auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'), 
        name='reset_password'),
    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_sent.html'), 
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_form.html'), 
        name='password_reset_confirm'),
    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), 
        name='password_reset_complete'),

    path('privacy_policy/', views.privacy_policy, name='privacy_policy'), 
    path('terms_and_conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('advertise/', views.advertise, name='advertise'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('about/', views.about, name='about'),
    
    path('articles/', LatestUpdates.as_view(), name='latest_updates'),
    path('articles/<slug:slug>/<int:pk>/', views.BlogDetailView, name='article_detail'),
    path('articles/<slug:slug>/<int:pk>/update/', BlogUpdateView.as_view(), name='article_update'),
    path('articles/<slug:slug>/<int:pk>/delete/', BlogDeleteView.as_view(), name='article_delete'),
    path('article_form/', BlogCreateView.as_view(), name='article_form'),
    path('categories/<category_slug>/', views.BlogCategory, name='category'),

    path('', BlogListView.as_view(), name='homepage'),
]

"""
    path('forum/', ForumListView.as_view(), name='forum_list'),
    path('forum/<slug:slug>/<int:pk>/', views.ForumDetailView, name='forum_detail'),
    path('like_forum/', views.like_forum, name='like_forum'),
    path('forum/<slug:slug>/<int:pk>/update/', ForumUpdateView.as_view(), name='forum_update'),
    path('forum/<slug:slug>/<int:pk>/update_image/', views.ForumImageUpdate, name='forum_update_image'),
    path('forum/<slug:slug>/<int:pk>/favourite_posts/', views.FavouritePost, name='favourite_posts'),
    path('forum/favourite_posts/', views.FavouritePostView, name='favourite_posts_view'),
    path('forum/<slug:slug>/<int:pk>/delete/', ForumDeleteView.as_view(), name='forum_delete'),
    path('delete_comment/<int:pk>/', ForumCommentDeleteView.as_view(), name='comment_delete'),
    path('forum_form/', views.ForumCreateView, name='forum_form'),
    path('sections/<section_slug>/', views.ForumSection, name='section'),

    path('<str:username>/', ProfileView.as_view(), name='profile_view'),
"""

techsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from tech.sitemaps import SITEMAPS


urlpatterns = [
    path('admin/', admin.site.urls),
   # path('', include('notice.urls')),
    path('', include('tech.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': SITEMAPS}),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech/models.py
from django.db import models, IntegrityError 
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from PIL import Image

User = get_user_model()

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default='default.jpg', max_length=500)
    first_name = models.CharField(max_length=50, blank=True, default='')
    last_name = models.CharField(max_length=50, blank=True, default='')
    bio = models.TextField(max_length=200, blank=True, default='')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_pic)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_pic)

    @property
    def imageURL(self):
        try:
            url = self.profile_pic.url
        except:
            url = ''
        return url
            

class Category(models.Model):
    category = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('category', args=[self.slug])


class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, max_length=500)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk': self.id, 'slug': self.slug})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Blog, self).save(*args, **kwargs)


"""
class Section(models.Model):
    section = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.section

    def get_absolute_url(self):
        return reverse('section', args=[self.slug])


class Forum(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    content = models.TextField()
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('forum_detail', kwargs={'pk': self.id, 'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class ForumComment(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('ForumComment', null=True, related_name='replies', on_delete=models.CASCADE)
    content = models.TextField(max_length=200)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp']

    def __str__(self):
        return '{} - {}'.format(self.forum.title, str(self.user.username))

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('forum_detail', kwargs={'pk': self.id,})


class ForumImages(models.Model):
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, max_length=500)

    def __str__(self):
        return self.forum.title + " Image"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image)

        if img.height > 400 or img.width > 400:
            output_size = (400, 400)
            img.thumbnail(output_size)
            img.save(self.image)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
"""

templates/techsite/forum/comment_delete.html
{% extends "base.html" %} 
{% block title %} Delete Comment | TechWif {% endblock %}
{% block content %}
<div class="container h-50 my-5">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card my-4">
            <div class="center">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <legend class="border-bottom mb-4">Delete Comment</legend>
                        <p>Are you sure you want to delete this comment?</p>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-outline-danger m-4 tf" type="submit">Yes, Delete</button>
                    </div>
            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/techsite/forum/comments.html
{% load crispy_forms_tags %}
{% load humanize %}
<div class="">
    {{ total_comments }} Comment{{ total_comments|pluralize }}
</div>

<hr>
<div class="mt-2">
    <form method="POST" class="comment-form" action="./#result">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <input type="hidden" name="entry" value="{{ forum.pk }}">
        {% if user.is_authenticated %}
            <input type="submit" value="Submit" class="btn btn-secondary tf">   
        {% else %}
            <input type="submit" value="Submit" class="btn btn-secondary tf" disabled>
        {% endif %}
    </form>
</div>
<hr>
{% if user.is_authenticated %}
{% else %}
<div class="mt-2">
    <a href="{% url 'login' %}" class="btn btn-primary btn-block center tf">Login to comment or like post.</a>
</div>
<hr>
{% endif %}

{% for message in messages %}
<div class="center alert">
    <div class="d-flex justify-content-center links">
        <p id="messages">{{message}}</p>
    </div>
    <hr>
</div>
{% endfor %}

<div class="infinite-container">
    {% for comment in comments %}
    <div class="infinite-item" id="result">
        <blockquote class="mt-2" style="border-color: grey">
            <p><small>{{ comment.content|safe|linebreaks|urlizetrunc:40 }}</small></p>
            <footer class="blockqoute-footer"><small>by <cite title="Source Title"><a href="{% url 'profile_view' comment.user %}">{{ comment.user }}</a></cite> | {{ comment.timestamp|naturaltime }}</small>
                {% if comment.user == request.user or user.is_superuser %}
                    <a href="{% url 'comment_delete' comment.id %}"><i class="fas fa-trash-alt" style="color: crimson;"></i></a>
                {% endif %}
                <button type="button" name="button" class="reply-btn btn btn-sm p-1 ml-2 tf">{{ comment.replies.count }} Repl{{ comment.replies.count|pluralize:"y,ies" }}</button>
            </footer>
            <hr>
        </blockquote>

        <div class="replied-comments container mt-2" style="display:none;">
            {% for reply in comment.replies.all %}
            <blockquote style="border-color: grey">
                <p><small>{{ reply.content|safe|linebreaks|urlizetrunc:40 }}</small></p>
                <footer class="blockqoute-footer"><small>by <cite title="Source Title"><a href="{% url 'profile_view' reply.user %}">{{ reply.user }}</a></cite> | {{ reply.timestamp|naturaltime }}</small>
                    {% if reply.user == request.user or user.is_superuser %}
                        <a href="{% url 'comment_delete' comment.id %}"><i class="fas fa-trash-alt" style="color: crimson;"></i></a>
                    {% endif %}
                </footer>
                <hr>
            </blockquote>
            {% endfor %}
            <div class="mt-2">
                <form method="POST" class="reply-form" action="./#result">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {{ comment_form|crispy }}
                    <input type="hidden" name="entry" value="{{ forum.pk }}">
                    {% if user.is_authenticated %}
                        <input type="submit" value="Submit" class="btn btn-secondary tf">   
                    {% else %}
                        <input type="submit" value="Submit" class="btn btn-secondary tf" disabled>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="container" style="text-align: center;">
    {% if comments.has_other_pages %}
    {% if comments.has_next %}
        <a class="infinite-more-link" href="?page={{ comments.next_page_number }}"></a>
    {% endif %}  
    {% endif %}
    
    <div class="loading" style="display: none;">
        Loading...
    </div>
</div>

templates/techsite/forum/favourite_posts.html
{% extends 'base.html' %}
{% block title %} Favourites | TechWif {% endblock %}
{% block content %}

<div class="container">
    <div class="mt-4">
        <form class="form-inline" action="{% url 'forum_list' %}" method="GET">
            <input class="" type="text" placeholder="Search forum" aria-label="Search" name="q" value="{{ request.GET.q }}">
            <button class="btn btn-secondary tf" type="submit">Search</button>
        </form>
    </div>
    <hr>
    
    <div class="forum-wrapper mt-0">
        <div>
            <h4 class="mt-2" id="main-articles">Favourite Posts</h4>
        </div>
        <div>
            <div class="infinite-container p-0 my-4">
                {% for forum in favourite_posts %}
                <div class="media content-section article-text m-2 infinite-item">
                    <div class="media-body article-text">
                        <div class="article-metadata">
                            <a class="me-2" href="{% url 'profile_view' forum.author.username %}">{{ forum.author }}</a>
                            <small class="text-muted">{{ forum.created_date }}</small>
                            <small class="text-muted"> | </small>
                            <a href="{{ forum.section.get_absolute_url }}"><small>{{ forum.section }}</small></a>
                        </div>
                        <div>
                            <strong><a class="" href="{{ forum.get_absolute_url }}" class="btn btn-outline-secondary btn-sm btn-block" role="button">{{ forum.title|capfirst }}</a></strong>
                        </div>               
                    </div>       
                </div>
                {% empty %}
                <div class="card center m-4 p-4">
                    <h5>No favourite posts yet.</h5>
                </div>
                {% endfor %}
            </div>

            <div class="container" style="text-align: center;">
                {% if favourite_posts.has_next %}
                    <a class="infinite-more-link" href="?page={{ favourite_posts.next_page_number }}"></a>
                {% endif %} 
                
                <div class="loading mb-4" style="display: none;">
                    Loading...
                </div>
            </div>
        </div> 
    </div>             
</div>

{% endblock %}

{% block javascript %}
<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        handler: function(direction) {   
        },
        offset: 'bottom-in-view',

        onBeforePageLoad: function() {
            $('.loading').show();
        },
        onAfterPageLoad: function() {
            $('.loading').hide();
        }
    });

    $(document).ready(function(e){
        $(function(){
            setTimeout(function(){
                $('.alert').slideUp(2000);
            }, 5000);
        });
    });

</script>
{% endblock %}

templates/techsite/forum/forum_delete.html
{% extends "base.html" %} 
{% block title %} Delete Post | TechWif {% endblock %}
{% block content %}
<div class="container h-50 my-5">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card my-4">
            <div class="center">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <legend class="border-bottom mb-4">Delete Post</legend>
                        <p>Are you sure you want to delete this post?</p>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-outline-danger m-4 tf" type="submit">Yes, Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/techsite/forum/forum_detail.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}
{% load crispy_forms_tags %}
{% block title %} {{ forum.title }} | TechWif {% endblock %}
{% block meta_extend %}
    <meta property="og:title" content="{{ forum.title }}" />
    <meta property="og:site_name" content="TechWif" />
    <meta property="og:url" content="https://www.techwif.com/{{ forum.get_absolute_url }}" />
    <meta property="og:description" content="{{ forum.content|safe }}" />
    <meta property="og:type" content="article" />
    {% for f in forum.forumimages_set.all %}
    <meta property="og:image" content="{{ f.image.url }}" />
    {% endfor %}

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="TechWif" />
    <meta name="og:title" content="{{ forum.title }}" />
    <meta name="twitter:description" content="{{ forum.content }}" />
    <meta name="twitter:creator" content="/techwif" />
    {% for f in forum.forumimages_set.all %}
    <meta name="twitter:image" content="{{ f.image.url }}" />
    {% endfor %}
{% endblock %}
{% block content %}
    <script data-ad-client="ca-pub-4934423132077353" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <div class="container my-4">
        <div class="row w-100 mx-auto article-text">
            <div class="col-lg-6 mx-auto p-0">
                <div class="title-block">
                    <h4>{{ forum.title|capfirst }}</h4>
                    by <a href="{% url 'profile_view' forum.author.username %}">{{ forum.author }}</a>,
                    updated on {{ forum.created_date }}
                    <hr>
                    <div class="center">
                        {% for f in forum.forumimages_set.all %}
                            <img class="mt-2" width="100%" height="100%" src="{{ f.image.url }}" alt="">
                        {% endfor %}
                    </div>
                    <hr>
                    <div class="mt-2">
                        <ul class="social-share-grid">
                            <li>{% post_to_facebook object_or_url "<i class='fab fa-facebook fa-lg'></i>" %}</li>
                            <li>{% post_to_twitter forum.title object_or_url "<i class='fab fa-twitter fa-lg'></i>" %}</li>
                            <li>{% post_to_whatsapp object_or_url "<i class='fab fa-whatsapp fa-lg'></i>" %}</li>
                            <li>{% post_to_telegram forum.title object_or_url "<i class='fab fa-telegram fa-lg'></i>" %}</li>
                            <li>{% post_to_linkedin forum.title object_or_url "<i class='fab fa-linkedin fa-lg'></i>" %}</li>
                            <li>{% post_to_reddit forum.title object_or_url "<i class='fab fa-reddit fa-lg'></i>" %}</li>
                        </ul>   
                    </div>
                    <hr>
                </div>
                <div class="">
                    <div class="article-text">
                        {{ forum.content|safe|linebreaks|urlizetrunc:40 }}
                    </div>  
    
                    <div class="m-2 center">
                        {% if forum.author == user or user.is_superuser %}
                        <hr>
                        <a class="btn btn-secondary tf m-2" href="{% url 'forum_update' forum.slug forum.id %}"><i class="fas fa-edit"></i></a>
                        <!--
                        <a class="btn btn-secondary tf m-2" href="{% url 'forum_update_image' forum.slug forum.id %}"><i class="fas fa-camera"></i></a>
                        -->
                        <a class="btn btn-danger tf m-2" href="{% url 'forum_delete' forum.slug forum.id %}"><i class="fas fa-trash-alt"></i></a>
                        <hr>
                        {% endif %}
                    </div>  
                </div>
            </div>
            
            <div class="col-lg-6 mx-auto">
                <div class="form-inline">
                    <div id="like-section">
                        {% include 'techsite/forum/like_section.html' %}
                    </div>
                    
                    {% if request.user == user %}
                    <div id="favourite-section">
                        {% if is_favourite %}
                        <a href="{% url 'favourite_posts' forum.slug forum.id %}">Remove from favourites</a>
                        {% else %}
                        <a href="{% url 'favourite_posts' forum.slug forum.id %}">Add to favourites</a>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
                
                <div class="main-comment-section">
                    {% include 'techsite/forum/comments.html' %}
                </div>          
            </div>
        </div>             
    </div>

{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function(event){
        $(document).on('click', '#like', function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
                type: 'POST',
                url: '{% url "like_forum" %}',
                data: {'id':pk, 'csrfmiddlewaretoken': '{{ crsf_token }}' },
                dataType: 'json',
                success: function(response){
                    $('#like-section').html(response['form'])
                    console.log($('#like-section').html(response['form']));
                },
                error: function(rs, e){
                    console.log(rs.responseText);
                },
            });
        });
    });

    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        handler: function(direction) {   
        },
        offset: 'bottom-in-view',

        onBeforePageLoad: function() {
            $('.loading').show();
        },
        onAfterPageLoad: function() {
            $('.loading').hide();
        }
    });

    $(document).ready(function(e){
        $(function(){
            setTimeout(function(){
                $('.alert').slideUp(2000);
            }, 5000);
        });
    });

</script>
{% endblock %}

templates/techsite/forum/forum_form.html
{% extends "base.html" %}
{% block title %} Forum Form | TechWif {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container h-100 my-5">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card m-4">
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group"> 
                        {{ form|crispy }}
                        {{ formset|crispy }}
                    </fieldset>
                    <div class="form-group d-grid center mt-2">
                        <button class="btn btn-secondary tf" type="submit">Submit</button>
                    </div>
                </form>
            </div>

            {% if form.errors %}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    <p id="messages">Error encountered!</p>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/techsite/forum/forum_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Forum | TechWif {% endblock %}
{% block meta_extend %}
    <meta name="description" content="Join the online community of techies. Create post, learn, share with others." />
	<meta property="og:image" content="{% static 'techwif\techwif-favicon.png' %}" />
{% endblock %}
{% block content %}
<script data-ad-client="ca-pub-4934423132077353" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<div class="container">
    <div class="mt-4">
        <form class="form-inline" action="{% url 'forum_list' %}" method="GET">
            <input class="" type="text" placeholder="Search forum" aria-label="Search" name="q" value="{{ request.GET.q }}">
            <button class="btn btn-secondary tf" type="submit">Search</button>
        </form>
    </div>
    <hr>
    
    <div class="forum-wrapper mt-0">
        <div>
            <h4 class="" id="main-articles">Forum Sections</h4>

            <div class="me-2">
                <div>
                    {% for item in sec_menu|dictsort:"section" %}
                        <a class="btn btn-outline-secondary btn-sm mt-2 tf" role="button" href="{% url 'section' item|slugify %}">{{ item }}</a>
                    {% endfor %}
                </div>
                <hr>
                {% if user.is_authenticated %}
                <div class="center">
                    <a class="btn btn-secondary tf" href="{% url 'forum_form' %}">Create post</a>
                </div>
                <hr>
                {% else %}
                <div class="center">
                    <a href="{% url 'login' %}" class="btn btn-primary tf">Login to create post</a>
                </div>
                <hr>
                {% endif %}
            </div>
        </div>
        <div>
            {% for forum in object_list %}
            <div class="media content-section article-text p-0 my-2">
                <!--
                <div>
                    <img class="rounded-circle  article-img" src="{{ forum.author.profile.profile_pic.url }}" width="70" height="70" alt="">
                </div>
                -->
                <div class="media-body article-text">
                    <div class="article-metadata">
                        <a class="me-2" href="{% url 'profile_view' forum.author.username %}">{{ forum.author }}</a>
                        <small class="text-muted">{{ forum.created_date }}</small>
                        <small class="text-muted"> | </small>
                        <a href="{{ forum.section.get_absolute_url }}"><small>{{ forum.section }}</small></a>
                    </div>
                    <div>
                        <strong><a class="" href="{{ forum.get_absolute_url }}" class="btn btn-outline-secondary btn-sm btn-block" role="button">{{ forum.title|capfirst }}</a></strong>
                    </div>               
                </div>       
            </div>
            {% empty %}
            <div class="card center m-4 p-4">
                <h5>No result found.</h5>
            </div>
            {% endfor %}
            <div class="container" style="text-align: center;">
                {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <a class="btn btn-outline-dark my-2 tf" href="?page=1">First</a>
                        <a class="btn btn-outline-dark my-2 tf" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}
                {% for num in page_obj.paginator.page_range %}
            
                    {% if page_obj.number == num %}
                        <a class="btn btn-outline-dark my-2  active" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class="btn btn-outline-dark my-2" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
            
                {% endfor %}
            
                {% if page_obj.has_next %}
                    <a class="btn btn-outline-dark my-2 tf" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-dark my-2 tf" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
                
                {% endif %}
            </div>
        </div> 
    </div>             
</div>

{% endblock %}

{% block javascript %}
<script>

    $(document).ready(function(e){
        $(function(){
            setTimeout(function(){
                $('.alert').slideUp(2000);
            }, 5000);
        });
    });

</script>
{% endblock %}

templates/techsite/forum/forum_update_image.html
{% extends "base.html" %}
{% block title %} Post Image | TechWif {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container h-100 my-5">
    <div class="d-flex justify-content-center h-100">
        <div class="box-element my-4">
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group"> 
                        {{ formset.management_form }}
                        {% for f in formset %}
                            {{ f|crispy }}
                        {% endfor %}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-secondary btn-block mt-4 tf" type="submit">Submit</button>
                    </div>
                </form>
            </div>

            {% if form.errors %}
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    <p id="messages">Error encountered!</p>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}